Repository Augora/Augora, pull requests merged in 2020-10, with the labels that each got.

#350 Compléter les éléments du "community profile"
  CODE_OF_CONDUCT.french.md
  CODE_OF_CONDUCT.md
Labels: notify, wip

#365 Placeholder fix
  src/images/ui-kit/missingfemale.png
  src/images/ui-kit/missingmale.png
  src/styles/components/deputies-list/_deputy.scss
  src/styles/templates/blocks/_block-general.scss
Labels: notify

#360 Rework tooltip components as a single one
  src/components/deputy/contact/Adresse.jsx
  src/components/deputy/map-district/MapDistrict.jsx
  src/components/tooltip/SimpleTooltip.tsx
  src/components/tooltip/Tooltip.tsx
  src/styles/app.scss
  src/styles/components/tooltip/_simple-tooltip.scss
  src/styles/components/tooltip/_tooltip.scss
  src/styles/templates/blocks/_block-contact.scss
  src/styles/templates/blocks/_block-map.scss
Labels: notify

#367 Add slack notification on build error
  .github/workflows/Build-PR.yml
  .github/workflows/Manual-CICD-Staging.yml
  .github/workflows/Push-CICD-Staging.yml
Labels: notify

#362 Fix console warnings
  gatsby-browser.js
  src/components/deputies-list/DeputiesList.js
  src/components/deputy/contact/Adresse.jsx
  src/components/deputy/contact/Contact.jsx
  src/components/deputy/map-district/MapDistrict.jsx
  src/components/faq/Question.js
  src/pages/faq.js
  src/styles/pages/_faq.scss
  src/styles/templates/blocks/_block-contact.scss
  yarn.lock
Labels: notify

#370 Feature/suppression eds
  src/components/deputies-list/deputies-list-utils.js
  src/hooks/deputies-filters/useDeputiesFilters.js
  src/images/logos/groupes-parlementaires/eds/eds_blanc.png
  src/images/logos/groupes-parlementaires/eds/eds_color.png
  src/images/logos/groupes-parlementaires/eds/eds_grand.png
  src/images/logos/groupes-parlementaires/eds/eds_noird.png
Labels: notify

#371 Fix filters
  src/components/deputies-list/deputies-list-utils.js
  src/hooks/deputies-filters/useDeputiesFilters.js
  src/images/logos/groupes-parlementaires/eds/eds_blanc.png
  src/images/logos/groupes-parlementaires/eds/eds_color.png
  src/images/logos/groupes-parlementaires/eds/eds_grand.png
  src/images/logos/groupes-parlementaires/eds/eds_noird.png
  src/styles/templates/blocks/_block-general.scss
Labels: notify

#364 Feature/button animations
  src/components/buttons/Button.tsx
  src/components/buttons/Input.tsx
  src/components/buttons/SearchBar.tsx
  src/components/deputies-list/DeputiesList.js
  src/components/deputies-list/filters/Filters.js
  src/styles/app.scss
  src/styles/components/_filters.scss
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_checkbox.scss
  src/styles/components/buttons/_reset.scss
  src/styles/components/deputies-list/_deputies-list.scss
  src/styles/components/deputies-list/_filters.scss
  src/styles/components/filters/_groupes.scss
  src/styles/components/filters/_search.scss
  src/styles/components/filters/_sexes.scss
  src/styles/components/tooltip/_tooltip.scss
  src/styles/global/_animations.scss
  src/styles/global/_variables.scss
Labels: enhancement, notify, wip

#373 Feature/filter component improvement
  src/components/buttons/Button.tsx
  src/components/buttons/Input.tsx
  src/components/deputies-list/DeputiesList.js
  src/components/deputies-list/filters/Filters.js
Labels: notify

#374 Feature/buttons enhancement
  src/components/buttons/ButtonIcon.tsx
  src/components/buttons/ButtonInput.tsx
  src/components/deputies-list/filters/Filters.js
  src/components/searchbar/SearchBar.tsx
  src/images/ui-kit/icon-mail.svg
  src/images/ui-kit/icon-twitter.svg
  src/images/ui-kit/icon-web.svg
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_icon.scss
  src/styles/components/filters/_sexes.scss
  src/styles/templates/_deputy.scss
  src/templates/deputy/deputy.tsx
Labels: enhancement, notify

#375 Rework on SEO component
  src/components/layout.js
  src/components/seo.js
  src/components/seo/seo-utils.ts
  src/components/seo/seo.tsx
  src/pages/404.js
  src/pages/about.js
  src/pages/faq.js
  src/pages/index.tsx
  src/pages/mention-legales.js
  src/templates/deputy/deputy.tsx
Labels: notify

#369 Feature/retry on gaphql fail
  .github/workflows/Schedule-CICD-StressTest.yml
  gatsby-config.js
  package.json
  yarn.lock
Labels: notify

#376 develop into master
  gatsby-config.js
  package.json
  src/components/buttons/Button.tsx
  src/components/buttons/ButtonIcon.tsx
  src/components/buttons/ButtonInput.tsx
  src/components/deputies-list/DeputiesList.js
  src/components/deputies-list/filters/Filters.js
  src/components/layout.js
  src/components/searchbar/SearchBar.tsx
  src/components/seo.js
  src/components/seo/seo-utils.ts
  src/components/seo/seo.tsx
  src/images/ui-kit/icon-mail.svg
  src/images/ui-kit/icon-twitter.svg
  src/images/ui-kit/icon-web.svg
  src/pages/404.js
  src/pages/about.js
  src/pages/faq.js
  src/pages/index.tsx
  src/pages/mention-legales.js
  src/styles/app.scss
  src/styles/components/_filters.scss
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_checkbox.scss
  src/styles/components/buttons/_icon.scss
  src/styles/components/buttons/_reset.scss
  src/styles/components/deputies-list/_deputies-list.scss
  src/styles/components/deputies-list/_filters.scss
  src/styles/components/filters/_groupes.scss
  src/styles/components/filters/_search.scss
  src/styles/components/filters/_sexes.scss
  src/styles/components/tooltip/_tooltip.scss
  src/styles/global/_animations.scss
  src/styles/global/_variables.scss
  src/styles/templates/_deputy.scss
  src/templates/deputy/deputy.tsx
  yarn.lock
Labels: notify

#380 Removes-unused-data-in-query
  src/context/deputies-filters/deputiesFiltersContext.js
  src/templates/deputy/deputy.tsx
Labels: notify

#377 Feature/update deps 2020 24 10
  package.json
  yarn.lock
Labels: dependencies
